{ pkgs, ...}:
{
  home.packages = with pkgs; [
    inkscape
    nodePackages.prettier
    libsForQt5.kolourpaint
    pyright
    google-fonts
    wineWowPackages.waylandFull
    lutris
    zoom-us
    networkmanagerapplet
    font-awesome
    obs-studio
    git-filter-repo
    neofetch
    htop
    socat
    python3
    firefox
    telegram-desktop
    discord
    webcord
    tree
    nodejs_22
    grc
    whatsapp-for-linux
    gnome-system-monitor
    nautilus
    spotify
    slurp
    vlc
    wf-recorder
    bash
    ffmpeg
    loupe
    mpv
    pwvucontrol
    blueberry
    nvtopPackages.full
  ];
}
