{ pkgs, ...}:
{
  home.packages = with pkgs; [
    libsForQt5.kolourpaint
    pyright
    google-fonts
    wineWowPackages.waylandFull
    lutris
    zoom-us
    networkmanagerapplet
    font-awesome
    obs-studio
    git-filter-repo
    neofetch
    htop
    socat
    python3
    firefox
    telegram-desktop
    webcord
    tree
    nodejs_22
    grc
    whatsapp-for-linux
    gnome.gnome-system-monitor
    gnome.nautilus
    spotify
    slurp
    vlc
    wf-recorder
    bash
    ffmpeg
    loupe
    mpv
    pwvucontrol
    blueman
    nvtopPackages.full
  ];
}
